import Head from 'next/head';
import Image from 'next/image';
import GradButton  from '../components/navigation/buttons';
import Navbar from '../components/navigation/navbar';
import HeroImage from '../components/images/hero';
import Grids, { IconsSection } from '../components/layouts/mainlayout';
import HeroSection from '../components/sections/hero';
import servicesSection from '../components/sections/services';
import TestPage from '../pages/test'
import MainLayout from '../components/layouts/mainlayout';

export default function Home() {
	return (
		<div >
			<Head>
				<title>Safecare Travel Clinic</title>
				<meta
					name="description"
					content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar/>
			<main >
			<HeroSection/>
			<servicesSection/>	
			</main>
		</div>
	);
}
